name: Cloudflare Deployment

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  env:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            env
      - id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: env/.env
    outputs:
      cloudflare_projectname: ${{steps.dotenv.outputs.cloudflare_projectname || ''}}
  deploy:
    needs: env
    if: needs.env.outputs.cloudflare_projectname != ''
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: pnpm-setup
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "current"
          cache: "pnpm"
      - id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: env/.env
      - name: "Install"
        run: pnpm install
      - name: "Build"
        run: pnpm run build
      - name: "Cloudflare Config"
        run: cp ./.cloudflare/* ./dist/
      - name: Publish (Cloudflare)
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ steps.dotenv.outputs.cloudflare_projectname }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
