name: Github Labels

on:
  push:
    branches: [main]
    paths: "labels.json"
  workflow_dispatch:

jobs:
  deploy:
    name: Github Label Sync
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: "github-label-sync"
        run: npx github-label-sync --access-token ${{ secrets.GITHUB_TOKEN }} $GITHUB_REPOSITORY
