name: Github Labels

on:
  push:
    branches: [main]
    paths:
      - "labels.json"
      - ".github/workflows/labels.yml"
  workflow_dispatch:

jobs:
  deploy:
    name: Github Label Sync
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: "List wd"
        run: ls
      - name: "List parent"
        run: ls ..
      - name: "github-label-sync"
        run: npx github-label-sync --access-token ${{ secrets.GITHUB_TOKEN }} --labels labels.json $GITHUB_REPOSITORY
