name: Continuous Deployment

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  deploy:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            env
      - id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: env/.env
      - name: Run Tests
        uses: ./.github/workflows/test.yml
      - name: Deploy to Cloudflare
        if: ${{!!steps.dotenv.outputs.cloudflare_projectname}}
        uses: ./.github/workflows/cloudflare.yml
      - name: Deploy to Github Pages
        if: ${{!steps.dotenv.outputs.cloudflare_projectname}}
        uses: ./.github/workflows/gh-pages.yml
