name: Continuous Deployment

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
  env:
    needs: test
    name: Continuous Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            env
      - id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: env/.env
    outputs:
      cloudflare: ${{!!steps.dotenv.outputs.cloudflare_projectname}}
  cloudflare:
    needs: [test, env]
    if: ${{!!needs.env.outputs.cloudflare}}
    uses: ./.github/workflows/cloudflare.yml
  gh-pages:
    needs: [test, env]
    if: ${{!needs.env.outputs.cloudflare}}
    uses: ./.github/workflows/gh-pages.yml
